In [14]:
import pprint
import torch
import torch.nn as nn

In [13]:
transformer_model = nn.Transformer(nhead=16, num_encoder_layers=12)
pprint(transformer_model)

NameError: name 'pprint' is not defined

In [1]:
import timm

In [15]:
model_names = timm.list_models(pretrained= True)
from pprint import pprint
pprint(model_names)

['adv_inception_v3',
 'cait_m36_384',
 'cait_m48_448',
 'cait_s24_224',
 'cait_s24_384',
 'cait_s36_384',
 'cait_xs24_384',
 'cait_xxs24_224',
 'cait_xxs24_384',
 'cait_xxs36_224',
 'cait_xxs36_384',
 'coat_lite_mini',
 'coat_lite_small',
 'coat_lite_tiny',
 'coat_mini',
 'coat_tiny',
 'convit_base',
 'convit_small',
 'convit_tiny',
 'cspdarknet53',
 'cspresnet50',
 'cspresnext50',
 'deit_base_distilled_patch16_224',
 'deit_base_distilled_patch16_384',
 'deit_base_patch16_224',
 'deit_base_patch16_384',
 'deit_small_distilled_patch16_224',
 'deit_small_patch16_224',
 'deit_tiny_distilled_patch16_224',
 'deit_tiny_patch16_224',
 'densenet121',
 'densenet161',
 'densenet169',
 'densenet201',
 'densenetblur121d',
 'dla34',
 'dla46_c',
 'dla46x_c',
 'dla60',
 'dla60_res2net',
 'dla60_res2next',
 'dla60x',
 'dla60x_c',
 'dla102',
 'dla102x',
 'dla102x2',
 'dla169',
 'dm_nfnet_f0',
 'dm_nfnet_f1',
 'dm_nfnet_f2',
 'dm_nfnet_f3',
 'dm_nfnet_f4',
 'dm_nfnet_f5',
 'dm_nfnet_f6',
 'dpn68',
 'dpn

In [16]:
import timm
model = timm.create_model('vit_base_patch16_224', pretrained=True, num_classes=2)
# model.eval()
pprint(model)

VisionTransformer(
  (patch_embed): PatchEmbed(
    (proj): Conv2d(3, 768, kernel_size=(16, 16), stride=(16, 16))
    (norm): Identity()
  )
  (pos_drop): Dropout(p=0.0, inplace=False)
  (blocks): Sequential(
    (0): Block(
      (norm1): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
      (attn): Attention(
        (qkv): Linear(in_features=768, out_features=2304, bias=True)
        (attn_drop): Dropout(p=0.0, inplace=False)
        (proj): Linear(in_features=768, out_features=768, bias=True)
        (proj_drop): Dropout(p=0.0, inplace=False)
      )
      (drop_path): Identity()
      (norm2): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
      (mlp): Mlp(
        (fc1): Linear(in_features=768, out_features=3072, bias=True)
        (act): GELU()
        (fc2): Linear(in_features=3072, out_features=768, bias=True)
        (drop): Dropout(p=0.0, inplace=False)
      )
    )
    (1): Block(
      (norm1): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
      (attn

In [56]:
vit_model = nn.Sequential(*list(model.children())[1:]) #丢弃PatchEmbed层，直接输入(B,)

In [57]:
from torchsummary import summary
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
vit_model=vit_model.to(device)
summary(vit_model, (17,768))

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
           Dropout-1              [-1, 17, 768]               0
         LayerNorm-2              [-1, 17, 768]           1,536
            Linear-3             [-1, 17, 2304]       1,771,776
           Dropout-4           [-1, 12, 17, 17]               0
            Linear-5              [-1, 17, 768]         590,592
           Dropout-6              [-1, 17, 768]               0
         Attention-7              [-1, 17, 768]               0
          Identity-8              [-1, 17, 768]               0
         LayerNorm-9              [-1, 17, 768]           1,536
           Linear-10             [-1, 17, 3072]       2,362,368
             GELU-11             [-1, 17, 3072]               0
          Dropout-12             [-1, 17, 3072]               0
           Linear-13              [-1, 17, 768]       2,360,064
          Dropout-14              [-1, 

In [25]:
import tensorwatch as tw
tw.draw_model(model, [1, 3, 224, 224])

AttributeError: 'torch._C.Node' object has no attribute 'ival'

In [17]:
pprint(list(model.children())[2:])

[Sequential(
  (0): Block(
    (norm1): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
    (attn): Attention(
      (qkv): Linear(in_features=768, out_features=2304, bias=True)
      (attn_drop): Dropout(p=0.0, inplace=False)
      (proj): Linear(in_features=768, out_features=768, bias=True)
      (proj_drop): Dropout(p=0.0, inplace=False)
    )
    (drop_path): Identity()
    (norm2): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
    (mlp): Mlp(
      (fc1): Linear(in_features=768, out_features=3072, bias=True)
      (act): GELU()
      (fc2): Linear(in_features=3072, out_features=768, bias=True)
      (drop): Dropout(p=0.0, inplace=False)
    )
  )
  (1): Block(
    (norm1): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
    (attn): Attention(
      (qkv): Linear(in_features=768, out_features=2304, bias=True)
      (attn_drop): Dropout(p=0.0, inplace=False)
      (proj): Linear(in_features=768, out_features=768, bias=True)
      (proj_drop): Dropout(p=0.0, inpla

In [20]:
vit_model = nn.Sequential(*list(model.children()))  #丢弃PatchEmbed层，直接输入

In [21]:
print("Model's state_dict:")
for param_tensor in vit_model.state_dict():
    print(param_tensor, "\t", vit_model.state_dict()[param_tensor].size())

print()


Model's state_dict:
0.proj.weight 	 torch.Size([768, 3, 16, 16])
0.proj.bias 	 torch.Size([768])
2.0.norm1.weight 	 torch.Size([768])
2.0.norm1.bias 	 torch.Size([768])
2.0.attn.qkv.weight 	 torch.Size([2304, 768])
2.0.attn.qkv.bias 	 torch.Size([2304])
2.0.attn.proj.weight 	 torch.Size([768, 768])
2.0.attn.proj.bias 	 torch.Size([768])
2.0.norm2.weight 	 torch.Size([768])
2.0.norm2.bias 	 torch.Size([768])
2.0.mlp.fc1.weight 	 torch.Size([3072, 768])
2.0.mlp.fc1.bias 	 torch.Size([3072])
2.0.mlp.fc2.weight 	 torch.Size([768, 3072])
2.0.mlp.fc2.bias 	 torch.Size([768])
2.1.norm1.weight 	 torch.Size([768])
2.1.norm1.bias 	 torch.Size([768])
2.1.attn.qkv.weight 	 torch.Size([2304, 768])
2.1.attn.qkv.bias 	 torch.Size([2304])
2.1.attn.proj.weight 	 torch.Size([768, 768])
2.1.attn.proj.bias 	 torch.Size([768])
2.1.norm2.weight 	 torch.Size([768])
2.1.norm2.bias 	 torch.Size([768])
2.1.mlp.fc1.weight 	 torch.Size([3072, 768])
2.1.mlp.fc1.bias 	 torch.Size([3072])
2.1.mlp.fc2.weight 	 torch.

In [7]:
import urllib
from PIL import Image
from timm.data import resolve_data_config
from timm.data.transforms_factory import create_transform

config = resolve_data_config({}, model=model)
transform = create_transform(**config)

url, filename = ("", "dog.jpg")
urllib.request.urlretrieve(url, filename)
img = Image.open(filename).convert('RGB')
tensor = transform(img).unsqueeze(0) # transform and add batch dimension

/home/diode/anaconda3/envs/my_torch/lib/python3.8/site-packages/torchvision/transforms/transforms.py:257: UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.
  warnings.warn(


In [11]:
print(tensor.size())

torch.Size([1, 3, 224, 224])


In [8]:
import torch
with torch.no_grad():
    out = model(tensor)
probabilities = torch.nn.functional.softmax(out[0], dim=0)
print(probabilities.shape)
# prints: torch.Size([1000])

torch.Size([1000])


In [9]:
# Get imagenet class mappings
url, filename = ("https://raw.githubusercontent.com/pytorch/hub/master/imagenet_classes.txt", "imagenet_classes.txt")
urllib.request.urlretrieve(url, filename) 
with open("imagenet_classes.txt", "r") as f:
    categories = [s.strip() for s in f.readlines()]

# Print top categories per image
top5_prob, top5_catid = torch.topk(probabilities, 5)
for i in range(top5_prob.size(0)):
    print(categories[top5_catid[i]], top5_prob[i].item())
# prints class names and probabilities like:
# [('Samoyed', 0.6425196528434753), ('Pomeranian', 0.04062102362513542), ('keeshond', 0.03186424449086189), ('white wolf', 0.01739676296710968), ('Eskimo dog', 0.011717947199940681)]

Samoyed 0.5055654644966125
Pomeranian 0.31216004490852356
keeshond 0.060011763125658035
Pekinese 0.01597055420279503
white wolf 0.012953994795680046


In [14]:
import numpy as np

In [20]:
a = np.arange(120.).reshape(3,2,4,5)
b = np.arange(120.).reshape(3,2,4,5)
 
# 语义解析：
# 输入a：4阶张量，下标为bhid
# 输入b: 4阶张量，下标为bhjd
# 输出o: 4阶张量，下标为bhij
# 隐含语义：对d进行求和，公式附于代码之后：
o = np.einsum('bhid,bhjd->bhij', a, b)
print(o.shape)


(3, 2, 4, 4)


In [25]:
print(np.sum(a[0,0,1,:]*b[0,0,1,:].T))
print(o[0,0,1,1])

255.0
255.0


In [8]:
import torch 
t = torch.rand(3,3) #随机生成一个tensor
print(t)
print(t.shape)
r = torch.unbind(t,dim=0)#dim = 0指定拆除的维度
print(r)
s = torch.unbind(t,dim=1)#dim = 1指定拆除的维度
print(s)

tensor([[0.6078, 0.3124, 0.5947],
        [0.3450, 0.1349, 0.8827],
        [0.9812, 0.3748, 0.6346]])
torch.Size([3, 3])
(tensor([0.6078, 0.3124, 0.5947]), tensor([0.3450, 0.1349, 0.8827]), tensor([0.9812, 0.3748, 0.6346]))
(tensor([0.6078, 0.3450, 0.9812]), tensor([0.3124, 0.1349, 0.3748]), tensor([0.5947, 0.8827, 0.6346]))


In [11]:
def drop_path(x, drop_prob: float = 0., training: bool = False):
    """Drop paths (Stochastic Depth) per sample (when applied in main path of residual blocks).
    This is the same as the DropConnect impl I created for EfficientNet, etc networks, however,
    the original name is misleading as 'Drop Connect' is a different form of dropout in a separate paper...
    See discussion: https://github.com/tensorflow/tpu/issues/494#issuecomment-532968956 ... I've opted for
    changing the layer and argument names to 'drop path' rather than mix DropConnect as a layer name and use
    'survival rate' as the argument.
    """
    if drop_prob == 0. or not training:
        return x
    keep_prob = 1 - drop_prob
    shape = (x.shape[0],) + (1,) * (x.ndim - 1)  # work with diff dim tensors, not just 2D ConvNets
    random_tensor = keep_prob + torch.rand(shape, dtype=x.dtype, device=x.device)
    random_tensor.floor_()  # binarize
    output = x.div(keep_prob) * random_tensor
    return output

In [39]:
def drop_path(x, drop_prob: float = 0., training: bool = False):
    """Drop paths (Stochastic Depth) per sample (when applied in main path of residual blocks).
    This is the same as the DropConnect impl I created for EfficientNet, etc networks, however,
    the original name is misleading as 'Drop Connect' is a different form of dropout in a separate paper...
    See discussion: https://github.com/tensorflow/tpu/issues/494#issuecomment-532968956 ... I've opted for
    changing the layer and argument names to 'drop path' rather than mix DropConnect as a layer name and use
    'survival rate' as the argument.
    """
    if drop_prob == 0. or not training:
        return x
    keep_prob = 1 - drop_prob
    shape = (x.shape[0],) + (1,) * (x.ndim - 1)  # work with diff dim tensors, not just 2D ConvNets
    random_tensor = keep_prob + torch.rand(shape, dtype=x.dtype, device=x.device)
    random_tensor.floor_()  # binarize
    output = x.div(keep_prob) * random_tensor
    return output

t = torch.rand(5,3,5) #随机生成一个tensor
print(t)
dt = drop_path(t, 11, True)
print(dt)

tensor([[[0.9378, 0.4521, 0.8406, 0.7869, 0.3964],
         [0.1137, 0.9675, 0.5701, 0.2221, 0.0729],
         [0.6036, 0.0851, 0.1466, 0.3652, 0.5866]],

        [[0.8572, 0.0210, 0.9551, 0.8797, 0.0433],
         [0.0696, 0.1387, 0.0579, 0.6885, 0.8274],
         [0.3953, 0.5798, 0.8748, 0.2505, 0.0199]],

        [[0.3884, 0.5439, 0.6301, 0.1447, 0.7654],
         [0.5371, 0.2055, 0.9017, 0.8197, 0.8602],
         [0.3711, 0.8924, 0.1424, 0.5873, 0.9300]],

        [[0.0019, 0.5562, 0.5870, 0.0367, 0.8611],
         [0.5079, 0.0713, 0.2364, 0.4917, 0.6602],
         [0.5049, 0.1970, 0.3299, 0.8698, 0.4369]],

        [[0.8740, 0.0685, 0.0114, 0.8118, 0.8106],
         [0.2367, 0.4326, 0.4672, 0.5138, 0.3092],
         [0.1055, 0.8105, 0.4843, 0.2616, 0.1116]]])
tensor([[[0.9378, 0.4521, 0.8406, 0.7869, 0.3964],
         [0.1137, 0.9675, 0.5701, 0.2221, 0.0729],
         [0.6036, 0.0851, 0.1466, 0.3652, 0.5866]],

        [[0.8572, 0.0210, 0.9551, 0.8797, 0.0433],
         [0.0696, 0

In [6]:
import math
print(math.floor(28/6))
print(1000//1000)

4
1


In [9]:
import numpy as np

In [19]:
import torch
a=torch.tensor([[1,2,3],[4,5,6]], dtype=torch.long)

In [20]:
b = []
b.append(a)
b.append(a)
print(b)

[tensor([[1, 2, 3],
        [4, 5, 6]]), tensor([[1, 2, 3],
        [4, 5, 6]])]


In [10]:
c=np.array(b)
d=torch.from_numpy(c)

ValueError: only one element tensors can be converted to Python scalars

In [25]:
d = torch.stack(b, dim=0)
print(d.shape[0])

2
